name: Build (MSVC)

on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: DepthResolve/DepthResolve.slnx

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@767f00a3f09872d96a0cb9fcd5e6a4ff33311330

      - name: Setup NuGet
        uses: NuGet/setup-nuget@26b21e5ac5447a90465b29dcd8df7decea1074e1

      - name: Restore NuGet packages (packages.config)
        run: nuget restore ${{env.SOLUTION_FILE_PATH}} -NonInteractive

      - name: Build Release
        run: msbuild /m /p:Configuration=Release ${{ env.SOLUTION_FILE_PATH }} /p:PostBuildEventUseInBuild=false

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: DepthResolve-msvc.zip
          path: |
            DepthResolve/Release/DepthResolve.dll
            DepthResolve/Release/DepthResolve.pdb
          retention-days: 1